name: GitHub Pages deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.FLUTTER_CHANNEL }}
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      
      - name: Deploy to GitHub Pages
        uses: erickzanardo/flutter-gh-pages@v6
        with:
          webRenderer: canvaskit